version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    # Must have linters
    # https://mailgun.atlassian.net/wiki/spaces/ENG/pages/4278943767/Go+Static+Code+Analysis+Linters#Must-have-linters
    - bodyclose
    - errcheck
    - govet
    - gosec
    - ineffassign
    - staticcheck

    # Good to have linters
    # https://mailgun.atlassian.net/wiki/spaces/ENG/pages/4278943767/Go+Static+Code+Analysis+Linters#Good-to-have-linters
    - gocritic
    - gomodguard
    - nilerr
    - nolintlint
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (io.ReadCloser).Close

    gocritic:
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - whyNoLint # checked by nolintlint linter
        - hugeParam # TODO(vtopc): configure(80 bytes is probably not so much) and enable.
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/pkg/errors:
              recommendations:
                - errors
                - github.com/mailgun/errors
              reason: Deprecated

    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    staticcheck:
      checks:
        - all
        - -SA1019 # TODO(vtopc): enable SA1019 before migration to Go 2.0.
        - -ST1003 # TODO(v2): enable in scaffold@v2 (breaking changes)

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - gocritic
          - gosec
        path: _test\.go
      - linters:
          - gocritic
        path: example
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 50

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
