// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structs.proto

/*
Package election is a generated protocol buffer package.

It is generated from these files:

	structs.proto

It has these top-level messages:

	ResetElectionReq
	ResetElectionResp
	ResignReq
	ResignResp
	HeartBeatReq
	HeartBeatResp
	VoteResp
	VoteReq
	SetPeersReq
	SetPeersResp
	GetStateReq
	GetStateResp
*/
package election

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Resets the current state of a node to 'candidate'
type ResetElectionReq struct {
}

func (m *ResetElectionReq) Reset()                    { *m = ResetElectionReq{} }
func (m *ResetElectionReq) String() string            { return proto.CompactTextString(m) }
func (*ResetElectionReq) ProtoMessage()               {}
func (*ResetElectionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResetElectionResp struct {
}

func (m *ResetElectionResp) Reset()                    { *m = ResetElectionResp{} }
func (m *ResetElectionResp) String() string            { return proto.CompactTextString(m) }
func (*ResetElectionResp) ProtoMessage()               {}
func (*ResetElectionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Asks the node to resign as leader
type ResignReq struct {
}

func (m *ResignReq) Reset()                    { *m = ResignReq{} }
func (m *ResignReq) String() string            { return proto.CompactTextString(m) }
func (*ResignReq) ProtoMessage()               {}
func (*ResignReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ResignResp struct {
	// True if the receiver is leader and stepped down
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ResignResp) Reset()                    { *m = ResignResp{} }
func (m *ResignResp) String() string            { return proto.CompactTextString(m) }
func (*ResignResp) ProtoMessage()               {}
func (*ResignResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResignResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Sent by the leader of the election to all followers
type HeartBeatReq struct {
	// The leader this heart beat is from
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// The current term of the leader
	Term uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
}

func (m *HeartBeatReq) Reset()                    { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()               {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HeartBeatReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HeartBeatReq) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

// Response to a heart beat request
type HeartBeatResp struct {
	// The follower who is responding
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// The term the heart beat is for
	Term uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
}

func (m *HeartBeatResp) Reset()                    { *m = HeartBeatResp{} }
func (m *HeartBeatResp) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatResp) ProtoMessage()               {}
func (*HeartBeatResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HeartBeatResp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HeartBeatResp) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type VoteResp struct {
	// The candidate who responded
	Candidate string `protobuf:"bytes,1,opt,name=candidate" json:"candidate,omitempty"`
	// The term this vote response is for
	Term uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	// If the Vote was granted by this node
	Granted bool `protobuf:"varint,3,opt,name=granted" json:"granted,omitempty"`
}

func (m *VoteResp) Reset()                    { *m = VoteResp{} }
func (m *VoteResp) String() string            { return proto.CompactTextString(m) }
func (*VoteResp) ProtoMessage()               {}
func (*VoteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VoteResp) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

func (m *VoteResp) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResp) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

// A vote request sent to all peers at
// the start of an election.
type VoteReq struct {
	// The candidate who is requesting the targets vote
	Candidate string `protobuf:"bytes,1,opt,name=candidate" json:"candidate,omitempty"`
	// The term this vote is for.
	Term uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
}

func (m *VoteReq) Reset()                    { *m = VoteReq{} }
func (m *VoteReq) String() string            { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()               {}
func (*VoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VoteReq) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

func (m *VoteReq) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

// Set the peers this node will consider during the election
type SetPeersReq struct {
	// A list of peers
	Peers []string `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *SetPeersReq) Reset()                    { *m = SetPeersReq{} }
func (m *SetPeersReq) String() string            { return proto.CompactTextString(m) }
func (*SetPeersReq) ProtoMessage()               {}
func (*SetPeersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetPeersReq) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type SetPeersResp struct {
}

func (m *SetPeersResp) Reset()                    { *m = SetPeersResp{} }
func (m *SetPeersResp) String() string            { return proto.CompactTextString(m) }
func (*SetPeersResp) ProtoMessage()               {}
func (*SetPeersResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// Get the current state of the node
type GetStateReq struct {
}

func (m *GetStateReq) Reset()                    { *m = GetStateReq{} }
func (m *GetStateReq) String() string            { return proto.CompactTextString(m) }
func (*GetStateReq) ProtoMessage()               {}
func (*GetStateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type GetStateResp struct {
	Leader string   `protobuf:"bytes,1,opt,name=leader" json:"leader,omitempty"`
	State  string   `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Peers  []string `protobuf:"bytes,3,rep,name=peers" json:"peers,omitempty"`
}

func (m *GetStateResp) Reset()                    { *m = GetStateResp{} }
func (m *GetStateResp) String() string            { return proto.CompactTextString(m) }
func (*GetStateResp) ProtoMessage()               {}
func (*GetStateResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetStateResp) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *GetStateResp) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetStateResp) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*ResetElectionReq)(nil), "ResetElectionReq")
	proto.RegisterType((*ResetElectionResp)(nil), "ResetElectionResp")
	proto.RegisterType((*ResignReq)(nil), "ResignReq")
	proto.RegisterType((*ResignResp)(nil), "ResignResp")
	proto.RegisterType((*HeartBeatReq)(nil), "HeartBeatReq")
	proto.RegisterType((*HeartBeatResp)(nil), "HeartBeatResp")
	proto.RegisterType((*VoteResp)(nil), "VoteResp")
	proto.RegisterType((*VoteReq)(nil), "VoteReq")
	proto.RegisterType((*SetPeersReq)(nil), "SetPeersReq")
	proto.RegisterType((*SetPeersResp)(nil), "SetPeersResp")
	proto.RegisterType((*GetStateReq)(nil), "GetStateReq")
	proto.RegisterType((*GetStateResp)(nil), "GetStateResp")
}

func init() { proto.RegisterFile("structs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xa9, 0x6d, 0x32, 0x49, 0x44, 0xa3, 0x48, 0x0e, 0x1e, 0xc2, 0x0a, 0x92, 0x93,
	0x17, 0x41, 0x0f, 0xde, 0x0a, 0xa2, 0x47, 0xd9, 0x42, 0x0f, 0xde, 0xd6, 0x64, 0x2c, 0x81, 0x36,
	0xd9, 0xec, 0x4c, 0xff, 0xbf, 0xec, 0x66, 0x4b, 0x8a, 0x78, 0xd0, 0xdb, 0x7c, 0xc3, 0x7b, 0x6f,
	0x66, 0xd8, 0x85, 0x8c, 0xd8, 0xec, 0x6b, 0xa6, 0x7b, 0x6d, 0x7a, 0xee, 0x45, 0x0e, 0xe7, 0x12,
	0x09, 0xf9, 0x65, 0x8b, 0x35, 0xb7, 0x7d, 0x27, 0x71, 0x10, 0x97, 0x70, 0xf1, 0xa3, 0x47, 0x5a,
	0x24, 0x10, 0x4b, 0xa4, 0x76, 0xe3, 0x14, 0x77, 0x00, 0x07, 0x20, 0x9d, 0x17, 0xb0, 0xa0, 0x7d,
	0x5d, 0x23, 0x51, 0x11, 0x94, 0x41, 0x15, 0xc9, 0x03, 0x8a, 0x47, 0x48, 0xdf, 0x50, 0x19, 0x5e,
	0xa2, 0x62, 0x89, 0x43, 0x9e, 0xc3, 0xec, 0xcb, 0xf4, 0x3b, 0x27, 0x8b, 0xa5, 0xab, 0x6d, 0x8f,
	0xd1, 0xec, 0x8a, 0x93, 0x32, 0xa8, 0x66, 0xd2, 0xd5, 0xe2, 0x09, 0xb2, 0x23, 0x1f, 0xe9, 0x3f,
	0x1b, 0xd7, 0x10, 0xad, 0x7b, 0x46, 0xe7, 0xb9, 0x81, 0xb8, 0x56, 0x5d, 0xd3, 0x36, 0x8a, 0xd1,
	0x1b, 0xa7, 0xc6, 0x6f, 0x6e, 0x7b, 0xc8, 0xc6, 0xa8, 0x8e, 0xb1, 0x29, 0xc2, 0xf1, 0x10, 0x8f,
	0xe2, 0x19, 0x16, 0x63, 0xee, 0xf0, 0xff, 0x58, 0x71, 0x0b, 0xc9, 0x0a, 0xf9, 0x1d, 0xd1, 0x90,
	0x0d, 0xb8, 0x82, 0x53, 0x6d, 0xeb, 0x22, 0x28, 0xc3, 0x2a, 0x96, 0x23, 0x88, 0x33, 0x48, 0x27,
	0x11, 0x69, 0x91, 0x41, 0xf2, 0x8a, 0xbc, 0x62, 0xe5, 0xa6, 0x0a, 0x09, 0xe9, 0x84, 0xa4, 0xf3,
	0x6b, 0x98, 0x6f, 0x51, 0x35, 0x68, 0xfc, 0x0a, 0x9e, 0x6c, 0x38, 0x59, 0x91, 0x5b, 0x20, 0x96,
	0x23, 0x4c, 0x23, 0xc3, 0xa3, 0x91, 0x4b, 0xf8, 0x88, 0xd0, 0x3f, 0xf1, 0xe7, 0xdc, 0x7d, 0x87,
	0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xdf, 0xef, 0x28, 0x1f, 0x02, 0x00, 0x00,
}
