name: Lint

on:
  pull_request:
    branches: [ master, main ]

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true # caching and restoring go modules and build outputs

      - name: Check that 'go mod tidy' was called before commit
        run: go mod tidy && git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-cache: true # cache/restore is done by actions/setup-go@v3 step
          args: -v
